services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DISCOVERY_URL: "http://discovery-service:8080"
  
  discovery-service:
    build:
      context: .
      dockerfile: DiscoveryService/Dockerfile
    environment:
      DISCOVER_SERVICES: "dummy-worker1, dummy-worker2"
      PERSISTENCE_FILE_PATH: "discovery.data"
      
  dummy-worker1:
    build:
      context: .
      dockerfile: DummyWorker/Dockerfile
    deploy:
      replicas: 2
      
  dummy-worker2:
    build:
      context: .
      dockerfile: DummyWorker/Dockerfile
    deploy:
      replicas: 2